version: '3.8'

services:
  predict_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9696:9696"
    volumes:
      - ./src:/app/src
      - ./model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  src:
  model:
